addpath('tests')
addpath('src')
output_path = [pwd '\bin'];
cd src

try
	
% 	mex '-LC:\Anaconda3\Library\lib'  ...
% 		-lz -O -v CFLAGS="$CFLAGS -std=c11" getmatvar_.c...
% 		extlib/mman-win32/mman.c...
% 		fileHelper.c...
% 		getPageSize.c...
% 		mapping.c...
% 		numberHelper.c...
% 		queue.c...
% 		chunkedData.c...
% 		mexPointerSetters.c...
% 		readMessage.c
	
	libdeflate_path = ['-L' pwd '\extlib\libdeflate\x64'];
	mex(libdeflate_path, '-llibdeflate', '-g', '-v', 'CFLAGS="$CFLAGS -std=c11"', '-outdir', output_path ,... 
		'getmatvar_.c',...
		'extlib/mman-win32/mman.c',...
		'fileHelper.c',...
		'getSystemInfo.c',...
		'mapping.c',...
		'numberHelper.c',...
		'queue.c',...
		'chunkedData.c',...
		'mexPointerSetters.c',...
		'readMessage.c')

	cd ..
	%loadlibrary('C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\pthreadVC2.dll','C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\pthread.h')
	clear libdeflate_path clear output_path

catch ME
	
	cd ..
	rethrow(ME)
	
end