addpath('tests')
addpath('src')
output_path = [pwd '\bin'];
cd src

try	

	libdeflate_path = ['-L' pwd '\extlib\libdeflate\x64'];
	if(strcmp(mex.getCompilerConfigurations('C','Selected').ShortName, 'mingw64'))
		mex(libdeflate_path, '-llibdeflate', '-O', '-v', 'CFLAGS="$CFLAGS -std=c11"', '-outdir', output_path ,... 
			'getmatvar_.c',...
			'extlib/mman-win32/mman.c',...
			'extlib/threadpool/thpool.c',...
			'fileHelper.c',...
			'getSystemInfo.c',...
			'mapping.c',...
			'numberHelper.c',...
			'queue.c',...
			'chunkedData.c',...
			'mexPointerSetters.c',...
			'readMessage.c')
	else
		pthreadvc2_path = ['-L' pwd '\extlib\pthreadvc2'];
		mex(libdeflate_path, pthreadvc2_path, '-llibdeflate', '-lpthreadVC2', ...
			'-O', '-v', 'CFLAGS="$CFLAGS -std=c11"', '-outdir', output_path ,... 
			'getmatvar_.c',...
			'extlib/mman-win32/mman.c',...
			'fileHelper.c',...
			'getSystemInfo.c',...
			'mapping.c',...
			'numberHelper.c',...
			'queue.c',...
			'chunkedData.c',...
			'mexPointerSetters.c',...
			'readMessage.c')
	end

	cd ..
	clear libdeflate_path clear output_path

catch ME
	
	cd ..
	rethrow(ME)
	
end