mex '-LC:\Anaconda3\Library\lib' '-LC:\Program Files (x86)\Visual Leak Detector\lib\Win64' -lzlib -g CFLAGS="$CFLAGS -std=c11 -Zi" getmatvar.c...
	extlib/mman-win32/mman.c...
	fileHelper.c...
	getPageSize.c...
	mapping.c...
	numberHelper.c...
	queue.c...
	chunkedData.c...
	mexPointerSetters.c...
	readMessage.c