mex '-LC:\Anaconda3\Library\lib' -lzlib -g CFLAGS="$CFLAGS -std=c11" getmatvar.c...
	extlib/mman-win32/mman.c...
	fileHelper.c...
	getPageSize.c...
	mapping.c...
	numberHelper.c...
	queue.c...
	chunkedData.c